name: yolo-dataset
channels:
  - conda-forge
dependencies:
  - opencv
  - pip
  - numpy
  - Pillow

  - pip:
    - sam-2 @ git+https://github.com/facebookresearch/segment-anything-2@c2ec8e14a185632b0a5d8b161928ceb50197eddc
    
